### PR TITLE
Notification bar

### PR DESCRIPTION
**Pull request by claudiosala80**
I added the bar
It seems ok in simulator and I tested on my watch
I added the font with the icon and adjusted the tiny font for Italy
I added permission to the manifest file

Please review if I didn't commit wrongly some files that normally you use as symbolic link

### CODE REVIEW

**Comment by samuelmr** [comment]
Thanks!

I just took a quick look.

You pushed both svg images and a png font for the icons. What's the purpose of the SVG's? Is the PNG font based on them?

Either you or your editor has reformatted the AboutTimeView.mc source file (replacing spaces with tabs or something) which makes it a bit hard to see what are the actual functional changes.

I'll review and test when I can find the time.

**Comment by claudiosala80** [comment]
Hello

Sorry for the code formatting, but was an engineer deformation!

Yes: svg are the source. I committed to have if needed

Thanks
Claudio

Il mar 11 feb 2020, 07:12 Samuel Rinnetmäki <notifications@github.com> ha
scritto:

**Comment by samuelmr** [comment]
Hi!

I’m sorry that it took me two months to merge the pull request. I finally managed to incorporate everything into my custom build system, compile and test the changes.

I pushed a new release of Italian and Finnish versions to the Garmin app store. I’ll build and release other language versions when I have the time.

Thanks again for great work and sorry again for the delay.

	Samuel

**Comment by claudiosala80** [comment]
Wonderful!

No issue: I suppose this is an hobby for you and so you do when you have
free time!

I will update during the day!

Thanks a lot
Claudiosala80

Il mar 7 apr 2020, 22:42 Samuel Rinnetmäki <notifications@github.com> ha
scritto:

**Pull request merged**
